# Generated by Django 4.1.7 on 2023-03-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moltres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pokemon',
            table=None,
        ),
    ]
